import {
  faBars,
  faCogs,
  faSignInAlt,
  faExclamationCircle,
  faStream,
  faCaretSquareDown,
  faDoorOpen,
  faDatabase,
  faCheck,
  faExclamation,
  faBook,
  faSortAlphaDown,
  faPlusCircle,
} from '@fortawesome/free-solid-svg-icons';
import {
  faTimesCircle,
  faPlusSquare,
  faEdit,
  faEye,
  faTrashAlt,
  faSave,
  faCheckCircle,
  faBookmark,
} from '@fortawesome/free-regular-svg-icons';
import { faDocker, faSymfony } from '@fortawesome/free-brands-svg-icons';

export const icons = {
  faBars,
  faCogs,
  faCheck,
  faSignInAlt,
  faTimesCircle,
  faExclamationCircle,
  faPlusSquare,
  faEdit,
  faEye,
  faTrashAlt,
  faStream,
  faCaretSquareDown,
  faSave,
  faDoorOpen,
  faCheckCircle,
  faDocker,
  faSymfony,
  faExclamation,
  faDatabase,
  faBookmark,
  faBook,
  faSortAlphaDown,
  faPlusCircle,
};
